// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Blofeld
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class GameScoreUpdated : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""GameScoreUpdated"",""namespace"":""Blofeld"",""fields"":[{""name"":""EntityId"",""type"":""int""},{""name"":""UpdateDate"",""type"":{""type"":""long"",""logicalType"":""timestamp-millis""}},{""name"":""EventType"",""type"":{""type"":""enum"",""name"":""DomainEntityEventType"",""namespace"":""Blofeld"",""symbols"":[""Unknown"",""Updated"",""Deleted""]}},{""name"":""Entity"",""default"":null,""type"":[""null"",{""type"":""record"",""name"":""GameScore"",""namespace"":""Blofeld"",""fields"":[{""name"":""GameId"",""type"":""int""},{""name"":""UserId"",""type"":""int""},{""name"":""Score"",""type"":""int""}]}]}]}");
		private int _EntityId;
		private System.DateTime _UpdateDate;
		private Blofeld.DomainEntityEventType _EventType;
		private Blofeld.GameScore _Entity;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return GameScoreUpdated._SCHEMA;
			}
		}
		public int EntityId
		{
			get
			{
				return this._EntityId;
			}
			set
			{
				this._EntityId = value;
			}
		}
		public System.DateTime UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				this._UpdateDate = value;
			}
		}
		public Blofeld.DomainEntityEventType EventType
		{
			get
			{
				return this._EventType;
			}
			set
			{
				this._EventType = value;
			}
		}
		public Blofeld.GameScore Entity
		{
			get
			{
				return this._Entity;
			}
			set
			{
				this._Entity = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.EntityId;
			case 1: return this.UpdateDate;
			case 2: return this.EventType;
			case 3: return this.Entity;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.EntityId = (System.Int32)fieldValue; break;
			case 1: this.UpdateDate = (System.DateTime)fieldValue; break;
			case 2: this.EventType = (Blofeld.DomainEntityEventType)fieldValue; break;
			case 3: this.Entity = (Blofeld.GameScore)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
